config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :user_likes
  resources :sellers
  devise_for :users
  resources :homes
  resources :funding_products
  resources :rewards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
	
	get '/sellers/:seller_id/homepage_seller', to: 'sellers#homepage_seller', as: :sellers_homepage_seller
	
	get '/sellers/:seller_id/makerpage_seller', to: 'sellers#makerpage_seller', as: :sellers_makerpage_seller
	
	get '/homes/:user_id/supporterpage', to: 'homes#supporterpage', as: :homes_supporterpage
	
	get '/rewards/:funding_product_id', to: 'rewards#show', as: :funding_products_rewardpage
	get '/rewards/:product_id_id', to: 'rewards#url_sub', as: :rewards_url
	
	#get '/:user_id/user_likes', to: 'user_likes#show', as: :show_user_like
	
	post 'funding_product/:funding_product_id/user_like' => 'user_likes#like_toggle'
	
	get 'sellers/:seller_id/edit', to: 'sellers#edit', as: :sellers_edit
	get 'sellers/:seller_id', to: 'sellers#show', as: :sellers_show
	
	root 'homes#index'
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
	has_many :funding_products
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: %i[ show edit update destroy ]

  # GET /sellers or /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1 or /sellers/1.json
  def show
  end
	
  # GET /sellers/new
  def new
    @seller = Seller.new
	@seller.seller_id=current_user.id
    @seller.user_id=current_user.id
  end

  # GET /sellers/1/edit
  def edit
  end
	
  def homepage_seller
	  @seller = Seller.find(params[:seller_id])
  end
	
  def makerpage_seller
	  @seller = Seller.find(params[:seller_id])
  end

  # POST /sellers or /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully created." }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1 or /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully updated." }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1 or /sellers/1.json
  def destroy
    @seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url, notice: "Seller was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seller_params
      params.require(:seller).permit(:seller_id, :user_id, :registration_num, :company_name, :ceo_name, :company_address, :ceo_email, :ceo_num)
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_with(model: seller, local: true) do |form| %>
  <% if seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<style>
	.field{
		text-align: center;
	}
	
	.actions{
		text-align: center;
	}
</style>

  <!--<div class="field">
    <%= form.label :seller_id %>
    <%= form.text_field :seller_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>-->


  <div class="field">
	<div class = "registration_num">사업자 등록 번호</div>
    <%= form.number_field :registration_num %>
  </div>

  <div class="field">
	  <div class = "company_name">상호/법인 명</div>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
	  <div class = "ceo_name">대표자</div>
    <%= form.text_field :ceo_name %>
  </div>

  <div class="field">
	  <div class = "company_address">소재지</div>
    <%= form.text_field :company_address %>
  </div>

  <div class="field">
	  <div class = "ceo_email">대표 이메일</div>
    <%= form.text_field :ceo_email %>
  </div>

  <div class="field">
	  <div class = "ceo_num">대표 번호</div>
    <%= form.number_field :ceo_num %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sellers/homepage_seller.erb
<p id="notice" style="margin-top: 0px; margin-bottom: 0px;" ><%= notice %></p>
<style>
	#left {
		display: flex;
	}
	
	#right {
		float: right;
	}
	
	#division {
		border-left: 1px solid #e8e6e6;
	}
	
	#center {
		text-align: center;
	}
	
	.supporter-project-info {
		border: 1px solid  #e8e6e6;
		border-radius: 20px 20px 20px 20px/ 20px 20px 20px 20px;
	}
	
	.My-page-profileBackground {
		height: 220px;
		width: 100%;
		background-color: #00C4C4;
	}
	
	.my-page-switch {
		background-color: #ffffff;
		border-radius: 12px 12px 0px 0px/ 12px 12px 0px 0px;
	}
	
	.My-page-content-wrapper {
		background-color: #ffffff;
	}
	
	.go-to-supporter-page {
		border: none;
		background-color: #ffffff;
		border-radius: 12px 12px 0px 0px/ 12px 12px 0px 0px;
		
	}
	
	.go-to-maker-page {
		border: none;
		background-color: #ffffff;	
	}
	
	.go-to-maker-page {
		border-radius: 12px 12px 0px 0px/ 12px 12px 0px 0px;
	}
	
	.go-to-open-funding {
		width: 728px;
		background-color: #00C4C4;
		border: none;
		height: 48px;
		color: #ffffff;
		text-align: center;	
		border-radius: 10px 10px 10px 10px/ 10px 10px 10px 10px;
		font-size: small;
	}
	
	.funding_button {
		font-size: medium;
		font-weight:bold;
		line-height: 48px;
		color: #ffffff
	}
	
	.my-project-size {
		color: #00C4C4
	}
</style>

<div class = "MainWrapper_content">
	<div class = "My-page" style="">
		<div class = "My-page-profileBackground" style="position:relative; width: 100%">
			<span style = "background-image : url(null);"></span>
		</div>
		<div class = "My-page-inner" style="margin-left:400px; margin-right:400px; position: relative; top: -180px;" >
			<div class = "my-page-header" style="height: 55px;">
				<div class="my-page-switch" id="right" style=" height: 55px;"  >
						<button data-event="supporter_mode" class="go-to-supporter-page" style=" height: 55px;">
							<%= link_to '서포터', homes_supporterpage_path(current_user.id) %>
						</button>
						<button data-event="maker_mode" class="go-to-maker-page" style="height: 55px;">
							<%= link_to '메이커', sellers_homepage_seller_path(current_user.id) %>
						</button>
				</div>
			</div>
			<div class = "My-page-content-wrapper" style="padding-top:15px;"  >
					<div class = "My-page-maker" id="left" style=" width:100%; padding-top: 25px;" >
						<div class = "My-page-profile-container" style="width: 30%" >
							<div class = "maker-profile" id = "center">
								<br>
									<h2>
										와디즈 메이커님	
									</h2>
								<br>
							</div>
							<div class="my-maker-page-container">
								<div class = "my-maker-page-content" id="center">
									<%= link_to "메이커 페이지", sellers_show_path(current_user.id)%>
								</div>
								<div class = "make-maker-page" id = "center">
										<strong><%= link_to "페이지 만들기 ", sellers_edit_path(current_user.id) %></strong>
								</div>
							</div>
							
						</div>
						<div class = "My-page-maker-content" id="division" style="width: 70%;  padding-left: 32px; padding-right: 32px; padding-top: 20px;" >
							<div class = "My-page-maker-section" style="height:433.5px" >
								<div class = "Tab-wrapper" style="height: 49px;">
									<!--<div class = "tab-menu" id="left">
										<button type="button" class="my-funding-product" style="margin-left: 10px; margin-right: 40px;">
											펀딩
										</button>
										<button type="button" class="my-funding-store" style="margin-left: 10px; margin-right: 40px;">
											스토어
										</button>
									</div>-->
									<div class="Tab-pannel" style="height: 321.4px;">
										<div class="my_project_product" style="padding-top: 10px; height:311.4px;">
											<h2 class = "my-project-title">
												만든펀딩
												<span class="my-project-size"><%= FundingProduct.where(seller_id_id: current_user.id).size%></span>
												
											</h2>
											<div class="show-my-funding-project" id="left"  style="margin-bottom:10px;">
												<div class = "my-funding-project">
													<div class = "my-project" style="margin-right:10px;">
														<a class="show-my-project" href="/funding_products/:product_id">
														<article>
														    <div class ="my-project-title-image">
																<img src="">
															</div>
															<div class ="my-project-title">
																<% %>
															</div>
															<!--<div class="TextContent_content">
																<h1 class="TextContent_title"><%= FundingProduct.where(seller_id_id: current_user.id) %></h1>
																	<p class="TextContent_summary">펀딩 준비 작성 중</p>
															</div>-->
														</article>
													</a>
													</div>
												</div>
											</div>
											<div class = "go-to-open-funding">
												<span class = "funding_button">
													
														<%= link_to "펀딩 오픈 신청하기", new_funding_product_path %>
													
													</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sellers</h1>

<table>
  <thead>
    <tr>
      <th>메이커</th>
      <th>User</th>
      <th>사업자 등록번호</th>
      <th>상호/법인명</th>
      <th>대표자명</th>
      <th>소재지</th>
      <th>대표 이메일</th>
      <th>대표 번호</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.seller_id %></td>
        <td><%= seller.user %></td>
        <td><%= seller.registration_num %></td>
        <td><%= seller.company_name %></td>
        <td><%= seller.ceo_name %></td>
        <td><%= seller.company_address %></td>
        <td><%= seller.ceo_email %></td>
        <td><%= seller.ceo_num %></td>
		
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/show.html.erb
<p id="notice" style="margin-top: 0px; margin-bottom: 0px;"><%= notice %></p>

<style>
	#center{
		text-align:center;
	}
	
	.maker-profile-page{
		width:770px; 

		
		margin: 0 auto;
	}
	.maker-profile-background {
		
		height:360px;
		
	}
	
	.maker-profile-background-image {
		background-color:#00C4C4;
		width:770px; 
		height:360px;
	}
	.maker-profile-main-page{
		height:325px;
		background-color:#ffffff;
		border-radius: 12px 12px 0px 0px/ 12px 12px 0px 0px;
	}
	.maker-base-info{
		padding-left: 15px;
		padding-top: 10px;
		height:49px;
	}
	.maker-page-content-container{
		height: 49px;
		background-color:#ffffff;
	}
</style>
<div style="background-color:#F9FAFB;">
<div class = "maker-profile-page">
	<div class = "maker-profile-page-container"  style="position:relative;" >
		<div class = "maker-profile-background" id="center">
			<div class = "maker-profile-background-image"> </div>
		</div>
	</div>
	<div class = "maker-profile-main-page"  style="padding: 20px 20px 20px 20px; position: relative; top: -10px ;">
		<div class = "maker-base-info">
			<div class = "maker-title" style="height:44px;">
				<h1>
					<%= @seller.company_name %>
				</h1>
			</div>
			<div class = "maker-tab-container" >
			<div class = "maker-info" style=" height:40px; border-bottom: 1px solid #e8e6e6 ">
				<h2>
					메이커 정보
				</h2>
			</div>
			<div class = "maker-info-detail" >
				<div class = "maker-company-name">
					<p>
  						<strong>상호/법인 명:</strong>
  						<%= @seller.company_name %>
					</p>
				</div>
				<div class = "maker-company_number">
					<p>
  						<strong>대표 전화:</strong>
  						<%= @seller.ceo_num %>
						</p>
				</div>
				<div class = "ceo-email">
					<p>
  						<strong>대표 이메일:</strong>
  						<%= @seller.ceo_email %>
					</p>
				</div>
				<div class = "maker-registration-num"   >
					<p>
						<strong>사업자 등록 번호:</strong>
  						<%= @seller.registration_num %>
					</p>
				</div>
			</div>
				
			</div>
		</div>
		
	</div>
	
</div>
</div>







<!--<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>-->

app/views/sellers/show_seller.erb
<p id="notice"><%= notice %></p>

<h1>
	메이커 페이지 채우고 <br><br>
	더 많은 기회를 얻으세요
</h1>

<p>
	<strong>기본 정보 입력하기</strong>
</p>

<p>
  <strong>사업자 등록번호</strong>
  <%= @sellers.registration_num %>
</p>

<p>
	<strong>상호/법인명</strong>
	<%= @sellers.company_name %>
</p>

<p>
	<strong>대표자명</strong>
	<%= @sellers.ceo_name %>
</p>

<p>
	<strong>소재지</strong>
	<%= @sellers.company_address %>
</p>

<p>
	<strong>대표 이메일</strong>
	<%= @sellers.ceo_email %>
</p>

<p>
	<strong>대표 번호</strong>
	<%= @sellers.ceo_num %>
</p>

<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>