config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :user_likes
  resources :sellers
  devise_for :users
  resources :homes
  resources :funding_products
  resources :rewards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
	
	get '/sellers/:seller_id/homepage_seller', to: 'sellers#homepage_seller', as: :sellers_homepage_seller
	
	get '/sellers/:seller_id/makerpage_seller', to: 'sellers#makerpage_seller', as: :sellers_makerpage_seller
	
	get '/homes/:user_id/supporterpage', to: 'homes#supporterpage', as: :homes_supporterpage
	
	get '/rewards/:funding_product_id', to: 'rewards#show', as: :funding_products_rewardpage
	get '/rewards/:product_id_id', to: 'rewards#url_sub', as: :rewards_url
	
	#get '/:user_id/user_likes', to: 'user_likes#show', as: :show_user_like
	
	post 'funding_product/:funding_product_id/user_like' => 'user_likes#like_toggle'
	
	get 'sellers/:seller_id/edit', to: 'sellers#edit', as: :sellers_edit
	get 'sellers/:seller_id', to: 'sellers#show', as: :sellers_show
	
	root 'homes#index'
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :funding_products
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: %i[ show edit update destroy ]

  # GET /rewards or /rewards.json
  def index
    @rewards = Reward.all
  end

  # GET /rewards/1 or /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards or /rewards.json
  def create
    @reward = Reward.new(reward_params)
	@reward = Reward.find(url_sub)
	#reward_params(permit(@funding_product.id))
	  
	#@reward.id = @funding_product.id
	#reward_params={ controller: 'rewards', action: 'show', id: @reward.product_id_id }
	  
	#@funding_product = FundingProduct.find(params[:product_id])
	#@reward.id = @funding_product.id
	#reward_params=(id: @reward.product_id_id)
	#reward_params.find(@funding_product.id)
	  
    respond_to do |format|
      if @reward.save
		format.html { redirect_to rewards_url_path(@reward), notice: "리워드 추가 완료 및 펀딩 오픈 성공" }
		#format.html { redirect_to controller: 'rewards', action: 'show', id: @reward.id }
		#format.html { redirect_to controller: 'rewards', id: @funding_product.id}
        #format.html { redirect_to reward_url(@reward), notice: "리워드 추가 완료 및 펀딩 오픈 성공" }
		#format.html { redirect_to funding_products_rewardpage_path(funding_products), notice: "리워드 추가 완료 및 펀딩 오픈 성공" }
        #format.html { redirect_to funding_product_url(@funding_product), notice: "리워드 추가 완료 및 펀딩 오픈 성공" }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1 or /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully updated." }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1 or /rewards/1.json
  def destroy
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url, notice: "Reward was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reward_params
	  params.require(:reward).permit(:reward_id, :product_id_id, :reward_price, :reward_name, :reward_content)
      #params.require(:reward).permit(:reward_id, :product_id_id, :reward_name, :reward_content, :reward_price, :order_id)
    end
	
	  def url_sub
	@reward = Reward.find(params[:product_id_id])
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward, local: true) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<div class=reward_product_id_id>제품 id</div>
    <%= form.text_field :product_id_id %>
  </div>

  <div class="field">
	<div class=reward_price>금액</div>
    <!--<%= form.label :reward_price %>-->
    <%= form.number_field :reward_price %>
  </div>

  <div class="field">
	<div class=reward_name>리워드명</div>
    <!--<%= form.label :reward_name %>-->
    <%= form.text_field :reward_name %>
  </div>

  <div class="field">
	<div class=reward_content>리워드 설명</div>
    <!--<%= form.label :reward_content %>-->
    <%= form.text_field :reward_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>리워드 선택</h1>

<table>
  <thead>
    <tr>
      <th>Reward</th>
      <th>Product</th>
      <th>Reward name</th>
      <th>Reward content</th>
      <th>Reward price</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= reward.reward_id %></td>
        <td><%= reward.product_id %></td>
        <td><%= reward.reward_name %></td>
        <td><%= reward.reward_content %></td>
        <td><%= reward.reward_price %></td>
        <td><%= reward.order_id %></td>
        <td><%= link_to 'Show', reward %></td>
        <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
        <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>리워드 설계</h1>
<h4>서포터님들에게 제공할 리워드를 입력해 주세요.</h4>

<div class="FundingGuide">
	<h4 class="FundingGuide_title">리워드 설계 조건</h4>
	<ul class="FundingConditionGuideSection_list__2hGJ2">
		<li class="FundingGuide_item_1">
			<h5 class="FundingGuide_1">정렬 순서</h5>
			<p class="FundingGuide_1_content">혜택이 좋은 순서대로 등록해 주세요.</p>
		</li>
		<li class="FundingGuide_item_2">
			<h5 class="FundingGuide_2">제한 수량</h5>
			<p class="FundingGuide_2_content">각 리워드별 제공할 수 있는 수량을 입력해 주세요. 제한된 수량이 모두 소진되면 이 리워드에 펀딩할 수 없어요.</p>
		</li>
		<li class="FundingGuide_item_3">
			<h5 class="FundingGuide_3">발송 시작일</h5>
			<div class="FundingGuide_3_contentbox">
				<p class="FundingGuide_3_content">프로젝트 종료일로부터 11개월 이내로 설계해 주세요.</p>
				<div color="basic" class="MessageBox">
					<div class="MessageBox_content">
						<ul>
							<li>설정한 발송 기간 내 리워드가 발송되지 않으면 서포터님들이 펀딩금 반환을 신청할 수 있으니 신중하게 선택해 주세요.</li>
							<li>프로젝트 종료일로부터 +11개월까지 발송이 시작되지 않으면 미발송 상태인 서포터님들의 펀딩금은 자동으로 반환(결제 취소)돼요.</li>
						</ul>
					</div>
				</div>
			</div>
		</li>
		<li class="FundingGuide_item_4">
			<h5 class="FundingGuide_4">옵션 조건</h5>
			<p class="FundingGuide_4_content">사이즈, 색상 등의 옵션 설정이 필요하면 추가해 주세요.</p>
		</li>
	</ul>
</div>

<%= render 'form', reward: @reward %>

<%= link_to 'Back', new_funding_product_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reward:</strong>
  <%= @reward.reward_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @reward.product_id %>
</p>

<p>
  <strong>Reward name:</strong>
  <%= @reward.reward_name %>
</p>

<p>
  <strong>Reward content:</strong>
  <%= @reward.reward_content %>
</p>

<p>
  <strong>Reward price:</strong>
  <%= @reward.reward_price %>
</p>

<p>
  <strong>Order:</strong>
  <%= @reward.order_id %>
</p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>