config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :user_likes
  resources :sellers
  devise_for :users
  resources :homes
  resources :funding_products
  resources :rewards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
	
	get '/sellers/:seller_id/homepage_seller', to: 'sellers#homepage_seller', as: :sellers_homepage_seller
	
	get '/sellers/:seller_id/makerpage_seller', to: 'sellers#makerpage_seller', as: :sellers_makerpage_seller
	
	get '/homes/:user_id/supporterpage', to: 'homes#supporterpage', as: :homes_supporterpage
	
	get '/rewards/:funding_product_id', to: 'rewards#show', as: :funding_products_rewardpage
	get '/rewards/:product_id_id', to: 'rewards#url_sub', as: :rewards_url
	
	#get '/:user_id/user_likes', to: 'user_likes#show', as: :show_user_like
	
	post 'funding_product/:funding_product_id/user_like' => 'user_likes#like_toggle'
	
	get 'sellers/:seller_id/edit', to: 'sellers#edit', as: :sellers_edit
	get 'sellers/:seller_id', to: 'sellers#show', as: :sellers_show
	
	root 'homes#index'
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all
	@funding_products = FundingProduct.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end
	
  def supporterpage
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to home_url(@home), notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to home_url(@home), notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:title, :content)
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<body>
<!--슬라이드 배너칸-->
	<div class="section">
		<input type="radio" name="slide" id="slide01" checked>
		<input type="radio" name="slide" id="slide02">
		<input type="radio" name="slide" id="slide03">

		<div class="slidewrap">
			<ul class="slidelist">
				<li>
					<a>
						<!--<label for="slide03" class="left"></label>-->
						<div class="image">
							<img src="/slide_image01.png" 
							 style="width: 1277px;
									height: 371.594;">linear-gradient(to top, black, white 10%)
						</div>
						<div class="textbox">
							<h3 style="margin-bottom: 0px;
									   margin-top: 10px;">지금만 누릴 수 있어요 <br> 72시간 한정 혜택 open</h3>
							<p style="margin-top: 5px;">펀딩</p>
						</div>
						<label for="slide02" class="right"></label>
					</a>
				</li>
				<li>
					<a>
						<label for="slide01" class="left"></label>
						<a href = "/funding_products/337">
						<div class="image">
							<img src="/slide_image02.png" 
							 style="width: 1277px;
									height: 371.594;">linear-gradient(to top, black, white 10%)
						</div>
							</a>
						<div class="textbox">
							<h3 style="margin-bottom: 0px;
									   margin-top: 10px;">2023년 새해를 위한 <br> 목표 달성 갓생템 펀딩</h3>
							<p style="margin-top: 5px;">펀딩</p>
						</div>
						<label for="slide03" class="right"></label>
					</a>
				</li>
				<li>
					<a>
						<label for="slide02" class="left"></label>
						<a href = "/funding_products/338">
						<div class="image">
							<img src="/slide_image03.png" 
							 style="width: 1277px;
									height: 371.594;">linear-gradient(to top, black, white 10%)
						</div>
						<div class="textbox">
							<h3 style="margin-bottom: 0px;
									   margin-top: 10px;">최강 한파 이겨낼 <br> 따뜻한 아이템 모음</h3>
							<p style="margin-top: 5px;">펀딩</p>
						</div>
						</a>
						<label for="slide01" class="right"></label>
					</a>
				</li>
			</ul>
		</div>
	</div>
	
<!--취향맞춤펀딩칸-->
	<div class="RecommendFundingProduct_table">
		<div class="RecommendFundingProduct_Title_1">
			<h1>취향 맞춤 펀딩 프로젝트</h1>
			<span class="RecommendFundingProduct_Title_1_description">지금 함께 만드는 성공</span>
		</div>
		<div class="MainCard_Home_Container">
		  <div class="MainCard_Home_list"
			   style="padding: 40px 100px">
			  <% @funding_products.each do |funding_product| %>
			  <div class="MainCard_item">
				  <div class="MainCard_item_info">
					  <a href = "/funding_products/<%= funding_product.id %>">
						  <!--<img src = "/:funding_product.avatar.url"/>-->
						  <span class="image">
							  <p><%= image_tag("#{funding_product.avatar}") %></p>
						  </span>
						  <p class="MainCard_title">
							  <strong><%= funding_product.title %></strong>
						  </p>
						  <div class="product_cb">
							  <span class="product_category"><%= funding_product.category_id %></span>
							  <span class="product_brand">| <%= funding_product.brand %></span>
						  </div>
						  <div>
							  <span class="MainCard_guideline"><hr/></span>
						  </div>
						  <div class="achieve">
							  <span class="achieve_rate"><%= funding_product.achieve_rate %>%</span>
							  <span class="achieve_money"><%= funding_product.achieve_money %>원</span>
						  </div>
						  <div class="deadline">
							  <span class="deadline_day"><%= funding_product.deadline %></span>
							  <span class="deadline_daytext">까지 펀딩 가능</span>
						  </div>
					  </a>
				  </div>
			  </div>
			  <% end %>
		  </div>
	  </div>
	</div>

</body>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @home.content %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/homes/supporterpage.erb
<p id="notice" style="margin-top: 0px; margin-bottom: 0px;"><%= notice %></p>
<style>
	#left {
		display: flex;
	}
	
	#right {
		float: right;
	}
	
	#division {
		border-left: 1px solid #e8e6e6;
	}
	
	#center {
		text-align: center;
	}
	
	.supporter-project-info {
		border: 1px solid  #e8e6e6;
		border-radius: 20px 20px 20px 20px/ 20px 20px 20px 20px;
	}
	
	.My-page-profileBackground {
		height: 220px;
		width: 100%;
		background-color: #00C4C4;
	}
	
	.my-page-switch {
		background-color: #ffffff;
		border-radius: 12px 12px 0px 0px/ 12px 12px 0px 0px;
	}
	
	.My-page-content-wrapper {
		background-color: #ffffff;
	}
	
	.go-to-supporter-page {
		border: none;
		background-color: #ffffff;
		border-radius: 12px 12px 0px 0px/ 12px 12px 0px 0px;
		
	}
	
	.go-to-maker-page {
		border: none;
		background-color: #ffffff;	
	}
	
	.go-to-maker-page {
		border-radius: 12px 12px 0px 0px/ 12px 12px 0px 0px;
	}
</style>

<div class = "MainWrapper_content">
	<div class = "My-page" style="">
		<div class = "My-page-profileBackground" style="position:relative; width: 100%">
			<span style = "background-image : url(null);"></span>
		</div>
		<div class = "My-page-inner" style="margin-left:400px; margin-right:400px; position: relative; top: -180px;" id="center">
			<div class = "my-page-header" style="height: 55px;">
				<div class="my-page-switch" id="right" style=" height: 55px;"  >
						<button data-event="supporter_mode" class="go-to-supporter-page" style=" height: 55px;">
							<%= link_to '서포터', homes_supporterpage_path(current_user.id) %>
						</button>

						<button data-event="maker_mode" class="go-to-maker-page" style="height: 55px;">
							<%= link_to '메이커', sellers_homepage_seller_path(current_user.id) %>
						</button>
				</div>
			</div>
			<div class = "My-page-content-wrapper" style="padding-top:15px;" >
					<div class = "My-page-supporter" id="left" style=" width:100%; padding-top: 25px;" >
						<div class = "My-page-profile-container" style="width: 30%" >
							<div class = "user-nickname" id = "center">
								
								유저 No. <%= current_user.id %><br>
								<%= current_user.nickname %> 님<br>
							</div>
						</div>
						<div class = "My-page-supporter-content" id="division" style="width: 70%;  padding-left: 32px; padding-right: 32px; padding-top: 20px;" >
							<div class = "My-page-supporter-section"  >
								<div class = "supporter-project-container" style="height: 318.5px; " >
									<div class = "supporter-project-info" id="left" style="width: 100%; height: 178.5px;">
										<div class = "supporter-funding" style="width: 25%; padding-top: 24px; padding-bottom: 24px; ">
											<a href="" id= "center">
												<b>
													<h1>
														0
													</h1>
												</b><br>
												펀딩
											</a>
										</div>
										<div class = "supporter-like" id="division" style="width: 25%;  padding-top: 24px; padding-bottom: 24px;" >
											<b id= "center">
												<h1>
													0
												</h1>
											</b><br>
											<%= link_to "나의 찜 목록", user_likes_path(current_user.id) %>
										</div>
										<div class = "supporter-order" id="division" style=" width: 25%;  padding-top: 24px; padding-bottom: 24px;" >
											<a href="" id= "center">
												<b>
													<h1>
														0
													</h1>
												</b><br>
												구매
											</a>
										</div>
										<div class = "supporter-find-startup" id="division" style="width: 25%;  padding-top: 24px; padding-bottom: 24px;" >
											<a href="" id= "center">
												<b>
													<h1>
														0
													</h1>
												</b><br>
												스타트업 찾기
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>