config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :user_likes
  resources :sellers
  devise_for :users
  resources :homes
  resources :funding_products
  resources :rewards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
	
	get '/sellers/:seller_id/homepage_seller', to: 'sellers#homepage_seller', as: :sellers_homepage_seller
	
	get '/sellers/:seller_id/makerpage_seller', to: 'sellers#makerpage_seller', as: :sellers_makerpage_seller
	
	get '/homes/:user_id/supporterpage', to: 'homes#supporterpage', as: :homes_supporterpage
	
	get '/rewards/:funding_product_id', to: 'rewards#show', as: :funding_products_rewardpage
	get '/rewards/:product_id_id', to: 'rewards#url_sub', as: :rewards_url
	
	#get '/:user_id/user_likes', to: 'user_likes#show', as: :show_user_like
	
	post 'funding_product/:funding_product_id/user_like' => 'user_likes#like_toggle'
	
	get 'sellers/:seller_id/edit', to: 'sellers#edit', as: :sellers_edit
	get 'sellers/:seller_id', to: 'sellers#show', as: :sellers_show
	
	root 'homes#index'
end

app/models/funding_product.rb
class FundingProduct < ApplicationRecord
	require 'carrierwave/orm/activerecord'
	has_many :sellers
	mount_uploader :avatar, AvatarUploader
	has_many :user_likes
	has_many :rewards
	
	
end

app/controllers/funding_products_controller.rb
class FundingProductsController < ApplicationController
  before_action :set_funding_product, only: %i[ show edit update destroy ]

  # GET /funding_products or /funding_products.json
  def index
    @funding_products = FundingProduct.all
  end

  # GET /funding_products/1 or /funding_products/1.json
  def show
  end

  # GET /funding_products/new
  def new
    @funding_product = FundingProduct.new
	@funding_product.seller_id_id=current_user.id
  end

  # GET /funding_products/1/edit
  def edit
  end

  # POST /funding_products or /funding_products.json
  def create
    @funding_product = FundingProduct.new(funding_product_params)

    respond_to do |format|
      if @funding_product.save
		format.html { redirect_to funding_product_url(@funding_product), notice: "펀딩 오픈 성공" }
		#format.html { redirect_to controller: 'rewards', action: 'new', id: @funding_product.id }
		#format.html { redirect_to funding_products_rewardpage_url(funding_product_id:@funding_product.id), notice: "리워드를 추가해주세요." }
        #format.html { redirect_to funding_products_rewardpage_url(@reward), notice: "리워드를 추가해주세요." }
        format.json { render :show, status: :created, location: @reward.new }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funding_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funding_products/1 or /funding_products/1.json
  def update
    respond_to do |format|
      if @funding_product.update(funding_product_params)
        format.html { redirect_to funding_product_url(@funding_product), notice: "Funding product was successfully updated." }
        format.json { render :show, status: :ok, location: @funding_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funding_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funding_products/1 or /funding_products/1.json
  def destroy
    @funding_product.destroy

    respond_to do |format|
      format.html { redirect_to funding_products_url, notice: "Funding product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funding_product
      @funding_product = FundingProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funding_product_params
      params.require(:funding_product).permit(:product_id,:seller_id_id, :avatar, :category_id, :title, :deadline, :achieve_rate, :achieve_money, :supporters_number, :brand, :product_detail)
    end
end

app/helpers/funding_products_helper.rb
module FundingProductsHelper
end

app/views/funding_products/_form.html.erb
<%= form_with(model: funding_product, local: true) do |form| %>
  <% if funding_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funding_product.errors.count, "error") %> prohibited this funding_product from being saved:</h2>

      <ul>
      <% funding_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>-->
  

  <div class="field">
    <%= form.label :seller_id_id %>
    <%= form.text_field :seller_id_id %>
  </div>

  <div class="field">
	<div class=funding_title>프로젝트 제목</div>
    <!--<%= form.label :title %>-->
    <%= form.text_field :title %>
  </div>

  <div class="field">
	<div class=representative_image>대표 이미지</div>
	<%= form.file_field :avatar %>
  </div>

  <div class="field">
	<div class=funding_category>카테고리</div>
    <!--<%= form.label :category_id %>-->
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
	<div class=funding_deadline>프로젝트 종료일</div>
    <!--<%= form.label :deadline %>-->
    <%= form.text_field :deadline %>
  </div>

  <div class="field">
	<div class=funding_achieve_rate>목표 달성률</div>
    <!--<%= form.label :achieve_rate %>-->
    <%= form.number_field :achieve_rate %>
  </div>

  <div class="field">
	<div class=funding_achieve_money>목표 달성 금액</div>
    <!--<%= form.label :achieve_money %>-->
    <%= form.number_field :achieve_money %>
  </div>

  <div class="field">
	<div class=funding_supporters_number>펀딩 참여 서포터 수</div>
    <!--<%= form.label :supporters_number %>-->
    <%= form.number_field :supporters_number %>
  </div>

  <div class="field">
	<div class=funding_brand>메이커 정보</div>
    <!--<%= form.label :brand %>-->
    <%= form.text_field :brand %>
  </div>

  <div class="field">
	<div class=funding_product_detail>프로젝트 요약</div>
    <!--<%= form.label :product_detail %>-->
    <%= form.text_field :product_detail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funding_products/edit.html.erb
<h1>Editing Funding Product</h1>

<%= render 'form', funding_product: @funding_product %>

<%= link_to 'Show', @funding_product %> |
<%= link_to 'Back', sellers_homepage_seller_path(current_user.id) %>

app/views/funding_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="padding: 20px 380px">펀딩 홈</h1>

<table>
  <tbody>
	  <div class="MainCard_Home_Container">
		  <div class="MainCard_Home_list"
			   style="padding: 40px 340px">
			  <% @funding_products.each do |funding_product| %>
			  <div class="MainCard_item">
				  <div class="MainCard_item_info">
					  <a href = "/funding_products/<%= funding_product.id %>">
						  <!--<img src = "/:funding_product.avatar.url"/>-->
						  <span class="image">
							  <p><%= image_tag("#{funding_product.avatar}") %></p>
						  </span>
						  <p class="MainCard_title">
							  <strong><%= funding_product.title %></strong>
						  </p>
						  <div class="product_cb">
							  <span class="product_category"><%= funding_product.category_id %></span>
							  <span class="product_brand">| <%= funding_product.brand %></span>
						  </div>
						  <div>
							  <span class="MainCard_guideline"><hr/></span>
						  </div>
						  <div class="achieve">
							  <span class="achieve_rate"><%= funding_product.achieve_rate %>%</span>
							  <span class="achieve_money"><%= funding_product.achieve_money %>원</span>
						  </div>
						  <div class="deadline">
							  <span class="deadline_day"><%= funding_product.deadline %></span>
							  <span class="deadline_daytext">까지 펀딩 가능</span>
						  </div>
						  <form action='/funding_product/<%= funding_product.id%>/user_like' method='post'>
							  <button>찜</button>
						  </form>
					  </a>
				  </div>
			  </div>
			
			  <% end %>
		  </div>
	  </div>
	  
  </tbody>
</table>

app/views/funding_products/new.html.erb
<h4>펀딩 준비 > 기본 정보</h4>

<h1>기본 정보</h1>
<h3>프로젝트를 대표하는 중요한 정보들을 입력해 주세요.</h3>

<%= render 'form', funding_product: @funding_product %>

<span>다음단계 | </span>

<%= link_to '리워드 설계하기', new_reward_path %><br>


<%= link_to 'Back', sellers_homepage_seller_path(current_user.id) %>

app/views/funding_products/show.html.erb
<p id="notice"><%= notice %></p>

<style>
	#image {
		height: 401px;
		width: 632px;
	}
	
	#left {
		display: flex;
	}
	
	#center {
		text-align: center;
	}
	
	.rate-bar {
		border-bottom: 2px solid #00C4C4;
	}
	
	.title-category{
		color: #00C4C4
	}
	
</style>

<div class = "reward-header"  style="margin: 60px 0">
	<p class = "title-category" id="center">
		<em><%= @funding_product.category_id %></em>
	</p>
	<h1 id="center"><%= @funding_product.title %></h1>
</div>
<div class = "reward-body-wrap">
<div class = "sub-funding-info-contents" style="margin-left:450px; margin-right:450px;" >
	<!--<div class = "funding_content-container" id="center">-->
	<div class = "funding-contents" id="left" style="width:100%">
	<div class = "sub-product-info-container" id="center" style="width:70%">
		<div class = "product-info">
			<div class = "tab-contents">
				<section class = "tab-info">
					<h3 class = "text-hidden" type="text-hidden">프로젝트 내용</h3>
					<div class = "view-slide-wrap" style="padding: 0">
						<div class = "view-slide-big image-slide slick-initialized slick-slider" >
						<div aria-live="polite" class="slick-list draggable" style="height: 401px;">
								<div class="slick-slide slick-current slick-active" id="center" style="width:632px;">
          							<div class="img-responsive" >
										 <%= image_tag(@funding_product.avatar.url) if @funding_product.avatar.url %>
									</div>
        						</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
	<div class = "right-contents-info" style="width:30%"  >
		<h3 class = "text-hidden" input type = "hidden">프로젝트 정보</h3>
		<div class = "product-info">
			<div class = "state-box">
				<h2 class = "remaining-day"><%= @funding_product.deadline %> 까지 펀딩 가능</h2>
				<p class="rate-bar" id="center" style="width:100%"><em></em></p>
				<p class = "achievement-rate" style = "margin-bottom: 16px;">
					<strong> <%= @funding_product.achieve_rate %> </strong> %달성</p>
				<p class="total-amount" style="margin-bottom: 16px;">
					<strong> <%= @funding_product.achieve_money %> </strong> 원 펀딩</p>
				<p class="total-supporter" style="margin-bottom: 16px;">
					<strong> <%= @funding_product.supporters_number %> </strong> 명의 서포터</p>
			</div>
			<div class="btn-wrap funding"  style="color:#00C4C4">
				<%= button_to "펀딩하기", rewards_path %>
            </div>
 
				<p>
  				<form action='/funding_product/<%= @funding_product.id%>/user_like' method='post'>
  					<button> 좋아요</button>  
  				</form>
		</div>
		</div>
	</div>
	</div>
	</div>
<!--</div>-->



<%= link_to 'Edit', edit_funding_product_path(@funding_product) %> |
<%= link_to 'Back', funding_products_path %>